services:
  # Backend service (Express Socket.IO with Bun runtime)
  - type: web
    name: backend
    runtime: node
    buildCommand: bun install
    startCommand: bun run server.ts
    plan: free
    rootDir: backend
    repo: https://github.com/danielgavidia/fractal-hangman
    branch: daniel/deployment

  # Frontend service (Vite React app)
  - type: web
    name: frontend
    runtime: node
    buildCommand: |
      bun install 
      bun run build
    startCommand: bun run preview
    plan: free
    envVars:
      - key: VITE_BASE_URL
        fromService:
          name: frontend
          type: web
          property: hostport
      - key: VITE_BACKEND_URL
        fromService:
          name: backend
          type: web
          property: hostport
    rootDir: frontend
    repo: https://github.com/danielgavidia/fractal-hangman
    branch: daniel/deployment
