services:
    - type: web
      name: backend
      env: node
      plan: free
      buildCommand: bun i
      startCommand: bun server.ts
      envVars:
          - key: DATABASE_URL
            sync: false
          - key: DIRECT_URL
            sync: true
          - key: PORT
            value: 10000
          - key: FRONTEND_URL
            fromService:
                type: web
                name: frontend
                envVarKey: RENDER_EXTERNAL_URL
      autoDeploy: true
      branch: daniel/deployment
    - type: web
      name: frontend
      env: static
      buildCommand: bun i && bun build
      staticPublishPath: /dist
      envVars:
          - key: VITE_BASE_URL
            fromService:
                type: web
                name: backend
                envVarKey: RENDER_EXTERNAL_URL
      autoDeploy: true
      branch: daniel/deployment
